# Generated by Django 4.2.7 on 2023-11-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diagnosticrecords_treatmentrecords_testrecords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediarecords',
            old_name='Field4',
            new_name='field4',
        ),
        migrations.RemoveField(
            model_name='mediarecords',
            name='inbody_url',
        ),
        migrations.RemoveField(
            model_name='mediarecords',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='mediarecords',
            name='xray_url',
        ),
        migrations.AddField(
            model_name='mediarecords',
            name='test_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='api.testrecords'),
        ),
    ]
