# Generated by Django 4.2.7 on 2023-11-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_field4_mediarecords_field4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticrecords',
            name='prescription_code',
        ),
    ]
